#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"
require "pathname"

ROOT = Pathname.new(__dir__).parent
CONTRACTS = ROOT.join("docs/contracts")
OUTPUT = CONTRACTS.join("gateway-openapi.yaml")
HTTP_METHODS = %w[get post put patch delete head options trace].freeze
SERVICE_FILES = {
  "Core" => "core-service-openapi.yaml",
  "Auth" => "auth-service-openapi.yaml",
  "Game" => "game-service-openapi.yaml"
}.freeze

def rewrite_refs(value, service)
  case value
  when Hash
    value.each do |key, child|
      if key == "$ref" && child.start_with?("#/components/schemas/")
        value[key] = child.sub("#/components/schemas/", "#/components/schemas/#{service}_")
      else
        rewrite_refs(child, service)
      end
    end
  when Array
    value.each { |child| rewrite_refs(child, service) }
  end
end

def route_policies
  source = ROOT.join("internal/httpapi/routes.go").read
  pattern = /\{http\.Method(\w+),\s*"([^"]+)",\s*(authUpstream|gameUpstream),\s*(\w+)\}/
  policies = {}
  source.scan(pattern).each do |method, path, upstream, access|
    key = [method.downcase, path]
    raise "duplicate Gateway route: #{key.join(' ')}" if policies.key?(key)

    unless %w[publicAccess authenticatedAccess ownUserAccess].include?(access)
      raise "unknown access policy for #{key.join(' ')}: #{access}"
    end
    policies[key] = { "upstream" => upstream, "access" => access }
  end
  raise "no Auth/Game routes found in internal/httpapi/routes.go" if policies.empty?

  policies
end

def gateway_error_responses(operation, access)
  responses = operation.fetch("responses")
  if access != "publicAccess"
    responses["401"] ||= { "description" => "Gateway rejected a missing or invalid access token." }
    responses["503"] ||= { "description" => "Gateway could not complete an access-token denylist check." }
  end
  if access == "ownUserAccess"
    responses["403"] ||= { "description" => "Gateway rejected a userId that differs from the access-token subject." }
  end
  responses["502"] ||= { "description" => "Gateway could not connect to the upstream service." }
  responses["504"] ||= { "description" => "Gateway timed out waiting for the upstream service." }

  responses.each_value do |response|
    response["headers"] ||= {}
    response["headers"]["X-Request-Id"] = {
      "description" => "UUID generated by the Gateway for this request.",
      "schema" => { "type" => "string", "format" => "uuid" }
    }
  end
end

def health_operation(name, ready: false)
  responses = {
    "200" => {
      "description" => ready ? "Gateway and configured dependencies are ready." : "Gateway process is healthy.",
      "content" => { "text/plain" => { "schema" => { "type" => "string", "example" => "ok\n" } } }
    }
  }
  if ready
    responses["503"] = {
      "description" => "Gateway or a configured dependency is not ready.",
      "content" => { "text/plain" => { "schema" => { "type" => "string", "example" => "not ready\n" } } }
    }
  end
  responses.each_value do |response|
    response["headers"] = {
      "X-Request-Id" => {
        "description" => "UUID generated by the Gateway for this request.",
        "schema" => { "type" => "string", "format" => "uuid" }
      }
    }
  end
  { "operationId" => name, "tags" => ["Gateway"], "security" => [], "responses" => responses }
end

policies = route_policies
seen_routes = {}
operation_ids = {}
output = {
  "openapi" => "3.1.0",
  "info" => {
    "title" => "AthleteLink API Gateway",
    "version" => "draft",
    "description" => "Draft public HTTP contract assembled from checked-in Core, Auth, and Game OpenAPI snapshots and the Gateway route table. The Gateway forwards upstream request and response bodies without mapping them. Core forwards any method under its configured request subtree; only operations in its snapshot are listed here. Core and Auth snapshots currently disagree with the agreed /api/v1 paths, and conformance with running services has not been verified. Gateway-generated errors have no prescribed response-body schema."
  },
  "servers" => [{ "url" => "/", "description" => "Gateway root; deployment origin is configured separately." }],
  "paths" => {},
  "components" => {
    "securitySchemes" => {
      "BearerAuth" => { "type" => "http", "scheme" => "bearer", "bearerFormat" => "JWT" }
    },
    "schemas" => {}
  }
}

SERVICE_FILES.each do |service, filename|
  source = YAML.load_file(CONTRACTS.join(filename))
  rewrite_refs(source, service)
  source.fetch("components").fetch("schemas").each do |name, schema|
    output["components"]["schemas"]["#{service}_#{name}"] = schema
  end

  source.fetch("paths").each do |source_path, path_item|
    next if service == "Auth" && source_path == "/health"

    public_path = "/api/v1#{source_path}"
    raise "duplicate public path: #{public_path}" if output["paths"].key?(public_path)

    output["paths"][public_path] = {}
    path_item.each do |method, operation|
      next unless HTTP_METHODS.include?(method)

      key = [method, public_path]
      if service == "Core"
        access = "authenticatedAccess"
        # Core expects this trusted header from the Gateway, never from its public caller.
        operation["parameters"]&.reject! do |parameter|
          parameter["in"] == "header" && parameter["name"].casecmp?("X-User-Id")
        end
      else
        policy = policies.fetch(key) { raise "snapshot route absent from Gateway: #{key.join(' ')}" }
        expected = "#{service.downcase}Upstream"
        raise "wrong upstream for #{key.join(' ')}" unless policy["upstream"] == expected

        access = policy["access"]
        seen_routes[key] = true
      end

      operation_id = operation.fetch("operationId")
      raise "duplicate operationId: #{operation_id}" if operation_ids.key?(operation_id)

      operation_ids[operation_id] = true
      operation["security"] = access == "publicAccess" ? [] : [{ "BearerAuth" => [] }]
      if access == "ownUserAccess"
        operation["description"] = [operation["description"], "Gateway requires userId to match the access-token subject."].compact.join("\n\n")
      end
      gateway_error_responses(operation, access)
      output["paths"][public_path][method] = operation
    end
  end
end

missing = policies.keys - seen_routes.keys
raise "Gateway routes absent from snapshots: #{missing.inspect}" unless missing.empty?

output["paths"]["/healthz"] = { "get" => health_operation("gatewayHealth") }
output["paths"]["/readyz"] = { "get" => health_operation("gatewayReadiness", ready: true) }

check_refs = lambda do |value|
  case value
  when Hash
    value.each do |key, child|
      if key == "$ref" && child.start_with?("#/components/schemas/")
        name = child.delete_prefix("#/components/schemas/")
        raise "unresolved schema reference: #{child}" unless output["components"]["schemas"].key?(name)
      else
        check_refs.call(child)
      end
    end
  when Array
    value.each { |child| check_refs.call(child) }
  end
end
check_refs.call(output)

document = "# Generated by scripts/build_gateway_openapi.rb from the checked-in service snapshots.\n"
document += "# Draft: /api/v1 Core and Auth compatibility with running services remains unverified.\n"
document += YAML.dump(output)

if ARGV == ["--check"]
  abort "#{OUTPUT} is stale; run ruby scripts/build_gateway_openapi.rb" unless OUTPUT.file? && OUTPUT.read == document
  puts "#{OUTPUT} is current"
elsif ARGV.empty?
  OUTPUT.write(document)
  puts "wrote #{OUTPUT}"
else
  abort "usage: ruby scripts/build_gateway_openapi.rb [--check]"
end
